import { Router } from "express";
import { listFoods,getFood,createFood,patchFood,deleteFood,listFoodNutrients,addFoodNutrient } from "../controllers/foods.controller.mjs";
const router=Router();
router.get("/",listFoods);
router.get("/:fdcId",getFood);
router.post("/",createFood);
router.patch("/:fdcId",patchFood);
router.delete("/:fdcId",deleteFood);
router.get("/:fdcId/nutrients",listFoodNutrients);
router.post("/:fdcId/nutrients",addFoodNutrient);
export default router;